config/routes.rb
Nuttyguy::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :customers
  resources :products, only: [:index, :show]
  resources :cart, only: [:index]
  resources :line_items, only: [ :create, :update, :destroy ]
  post 'cart/complete' => 'cart#complete'


  root 'products#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  include CheckoutSharedMethods
  
  belongs_to :customer

  has_many :line_items, as: :itemized 
  has_many :products, through: :line_items

  delegate :email, to: :customer


  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :cart
  has_many :orders
  
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :itemized, polymorphic: true
  belongs_to :product

  delegate :price, :title, :sku, to: :product
  delegate :image, to: :product, allow_nil: true

def subtotal
	price * quantity
end

end

app/models/order.rb
class Order < ActiveRecord::Base
	include CheckoutSharedMethods
  belongs_to :customer

  has_many :line_items, as: :itemized 
  has_many :products, through: :line_items, as: :itemized

  delegate :email, to:customer
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :title, :sku, :price, presence: true
	validates :price, numericality: true

# establishes many through relations in a model table line_items
	has_many :line_items
	has_many :carts, through: :line_items, source: :itemized, source_type: 'Cart'
	has_many :orders, through: :line_items, source: :itemized, source_type: 'Order'

	#gems

# for paper clip
	has_attached_file :image,  default_url: "/images/:style/missing.png"

# for FrindlyId
	extend FriendlyId
	friendly_id :title, use: [:slugged, :finders]


#for 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private 
	def load_cart

		return false unless customer_signed_in?
			current_customer.create_cart if current_customer.cart.nil?
			@cart = current_customer.cart
		
	end

		def load_cart_or_redirect_customer
			unless load_cart
			
			redirect_to new_customer_session_path, alert: "Please sign in to access your cart." and return 
		end

	end

  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

	before_action :load_cart_or_redirect_customer

def index
	@title = "Your Cart"
	
end

	def complete
		@order = Order.new(customer:current_customer)
		@order.line_items = @cart.line_items
		@order.save
		@cart.delete
		@title = "Your Order is Complete"
	end

#private method is only called internally (apply only in this controller not to another) 
#this is ok for Q add
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
		before_action :load_cart_or_redirect_customer

		def create

	product = Product.find(params[:product_id])
	if line_item = @cart.line_items.find { |li| li.product_id == product.id }
	line_item.quantity += params[:quantity].to_i
	else
	line_item =LineItem.new(cart: @cart, product: product, quantity: params[:quantity])
end
line_item.save

	redirect_to '/cart', notice: "#{product.title} was added to your cart." and return
end

def destroy
		li = LineItem.find(params[:id])
		product  = li.product
		li.delete
		redirect_to '/cart', notice: "#{product.title} was removed from your cart. " and return
	end	

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :prepare_redcarpet, :load_cart
	
	def index
		@get_nutty = true
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
		@title = @product.title
	end
	
	private
	
	def prepare_redcarpet
	#prep redcarpet to get markdown text
	@redcarpet = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
	
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/complete.html.erb
  <div class="row" id="cart-page">
    <div class="col-md-9">
        <div class="panel panel-default">
        <div class="panel-heading">Your Order is Complete</div>
        <div class="panel-body">
          <p>Thank you for shopping with us!  Our staff will be in touch soon to finalize your purchase.</p>
        </div>

        <table class="table">
          <thead>
            <tr>
              <th class="hidden-xs"></th>
              <th>Item</th>
              <th>Quantity</th>
              <th class="hidden-xs">Item Price</th>
              <th>Total Price</th>
            </tr>
          </thead>
          <tbody>
            <% @order.line_items.each do |line_item| %>
              <tr>
                <td id="thumbnail-div" class="hidden-xs">
                  <%= link_to line_item.product do %>
                    <%= image_tag line_item.image.url(:medium) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to line_item.product do %>
                    <p><%= line_item.title %></p>
                  <% end %>
                  <p class="gray-text">Item #<%= line_item.sku %></p>
                </td>
                <td>
                  <%= line_item.quantity %>
                </td>
                <td class="hidden-xs"><%= number_to_currency line_item.price %></td>
                <td class="total-price"><%= number_to_currency line_item.subtotal %></td>
              </tr>
            <% end %>
            <tr>
              <td>&nbsp;</td>
              <td>Subtotal</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td><%= number_to_currency @order.subtotal %></td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>Shipping</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>FREE</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>Estimated Tax</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>$0.00</td>
            </tr>
            <tr class="total-price">
              <td>&nbsp;</td>
              <td>Total</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td><%= number_to_currency @order.total %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div> <!-- End left column -->
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading">Sold To</div>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <p class="product">
                  <%= @order.email %>
                </p>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading">Customers Also Bought</div>
          <table class="table">
            <tbody>
              <tr>
                <td>
                  <p>
                    <%= link_to Product.first do %>
                      <%= image_tag Product.first.image.url(:medium) %>
                    <% end %>
                  </p>
                  <p class="product">
                    <%= link_to Product.first do %>
                      <%= Product.first.title %></p>
                    <% end %>
                </td>
              </tr>
            </tbody>
          </table>
      </div>
    </div> <!-- End right column -->
  </div> <!-- /.row --> 

app/views/cart/index.html.erb
	<div class="row" id="cart-page">
		<div class="col-md-9">
				<div class="panel panel-default">
				<div class="panel-heading">Your Cart</div>
				<div class="panel-body">
					<p>Thank you for shopping with us!</p>
				</div>

				<table class="table">
					<thead>
						<tr>
							<th class="hidden-xs"></th>
							<th>Item</th>
							<th>Quantity</th>
							<th class="hidden-xs">Item Price</th>
							<th>Total Price</th>
						</tr>
					</thead>
					<tbody>

					<% @cart.line_items.each do |line_item| %>
						<tr>
							<td id="thumbnail-div" class="hidden-xs">
								

								<%= link_to line_item.product do %>

							
								<%= image_tag line_item.image.url, alt: line_item.product.title, class: 'cart-thumbnail' %>
								<% end %>

							</td>
							<td>
								<%= link_to line_item.product do %>
								<p> <%= line_item.title %></p>
								<% end %>

								<p class="gray-text">Item <%= line_item.sku %></p>
							</td>
							<td><%= number_field_tag :quantity, line_item.quantity, min: 1, max: 100 %>

							<span class="glyphicon glyphicon-refresh"></span>update

							<%= link_to line_item_path(line_item), method: :delete do %>

							<span class="glyphicon glyphicon-remove"></span>remove
							<% end %>

							</td>
							<td class="hidden-xs"><%= number_to_currency line_item.price %></td>
							<td class="total-price"><%= number_to_currency line_item.subtotal %></td>
						</tr>

						<% end %>
							
					</tbody>
				</table>
			</div>
		</div> <!-- End left column -->
		<div class="col-md-3">
			<div class="panel panel-default" id="order-summary">
				<div class="panel-heading">Order Summary</div>
				<table class="table">
					<tbody>
						<tr>
							<td>Subtotal</td>
							<td><%= number_to_currency @cart.subtotal %></td>
						</tr>
						<tr>
							<td>Shipping</td>
							<td>FREE</td>
						</tr>
						<tr>
							<td>Estimated Tax</td>
							<td>$0.00</td>
						</tr>
						<tr class="total-price">
							<td>Total</td>
							<td><%= number_to_currency @cart.total %></td>
						</tr>
					</tbody>
				</table>
			</div>
			<%=  form_tag '/cart/complete', method: :post do  %>
			<%= submit_tag 'Checkout', id: 'check-out', class: "btn btn-red btn-lg" %>
			<% end %>
			
		</div> <!-- End right column -->
	</div> <!-- /.row --> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title><%= @title + ' | ' if @title %> That Nutty Guy</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width,initial-scale=1">

	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
<!-- putting in 'devise' gem flash notices here -->
 <% if flash[:alert] %>
      <div id="flash" class="alert"><%= flash[:alert] %></div>
    <% elsif flash[:notice] %>
      <div id="flash" class="notice"><%= flash[:notice] %></div>
    <% end %>


	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand ir" href="/">That Nutty Guy</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a href="/">Shop</a></li>
				<li><a href="#">Gift Finder</a></li>
				<li><a href="#">About</a></li>
				<li><a href="#">Contact</a></li>
			</ul>
			<div class="right-nav">
				<a href="#">Account</a> 
				<% if customer_signed_in? %>
				<%= link_to 'Sign Out', destroy_customer_session_path, method: :delete %>
				<% else %>
				<%= link_to 'Sign In', new_customer_session_path %>
				
				<% end %>
				<form class="navbar-form navbar-right">
					<div class="form-group">
						<a id="cart" href="/cart">
							<span class="glyphicon glyphicon-shopping-cart"></span>Cart
							<% if @cart %>
							<span class="badge"><%= @cart.line_items.count %> </span>
							<% end %>
						</a>
						<hr id="cart-hr" class="visible-xs">
						<input type="search" placeholder="Search" class="form-control" id="search">
					</div>
				</form>
			</div><!--/.right-nav -->
		</div><!--/.navbar-collapse -->
	</div><!--/.container -->
</div><!--/.navbar -->

<%= render 'shared/get_nutty' if @get_nutty %>

<div class="container">
	<div id="main" role="main">
	
    <% if flash[:alert] %>
      <div id="flash" class="alert"><%= flash[:alert] %></div>
    <% elsif flash[:notice] %>
      <div id="flash" class="notice"><%= flash[:notice] %></div>
    <% end %>

	<%= yield %>
	
	</div> <!-- /#main --> 
</div> <!-- /.container --> 
<footer>
	<div class="container">
		<div class="row">

			<div class="col-sm-3">
				<h6>Customer Service</h6>
				<ul>
					<li><a href="#">Shipping & Delivery</a></li>
					<li><a href="#">Order Status</a></li>
					<li><a href="#">Help</a></li>
				</ul>
			</div>

			<div class="col-sm-3">
				<h6>Policies</h6>
				<ul>
					<li><a href="#">Return Policy</a></li>
					<li><a href="#">Private Policy</a></li>
				</ul>
			</div>

			<div class="col-sm-4 col-sm-offset-2">
				<ul id="social-media">
					<a href="#"><span class="social-media facebook ir">Facebook</span></a>
					<a href="#"><span class="social-media twitter ir">Twitter</span></a>
					<a href="#"><span class="social-media instagram ir">Instagram</span></a>
					<a href="#"><span class="social-media google ir">Google+</span></a>
					<p id="copyright">© That Nutty Guy</p>
				</ul>
			</div>
			
		</div> <!-- /.row -->
	</div> <!-- /.container -->
</footer>

</body>
</html>

app/views/products/index.html.erb
<!-- nutty guy view of products created after creating the def action and the controller behavior -->

		<div id="featured">
			<h2 class="category">Featured Gifts</h2>
			<hr>
		</div>
		<div class="row">
			<% @products.each do |product|  %>
			<div class="col-md-3 col-sm-4 col-xs-12">
				<%= link_to product do %>
					<%= image_tag product.image.url, alt: product.title, class: "product" %>
					<p class="product"><%= product.title %></p>
				<% end %>
				<p class="gray-text"><%= number_to_currency product.price %></p>
			</div>
			<% end %>
		</div> <!--/.row -->



<!-- we chopped this from the application.html.erb file and replaced that with a yield to bring this dynamic index page content -->
<!-- I added in the product title as a dynamic element  -->

	

app/views/products/show.html.erb
#3rd Time Lucky ?

<div class="row">
		<div class="col-xs-12 hidden-sm hidden-xs">
			<ol class="breadcrumb">	
				<li><a href="/">Featured</a></li>
				<li class="active"><%= @product.title %> Bill</li>
			</ol>
			<hr>
		</div> 
	</div> <!-- /.row #breadcrumbs -->
	<div class="row" id="product-page">
		<div class="col-md-5 col-sm-6 col-xs-12">
			<div class="visible-xs"> <!-- mobile only -->
						<h1><%= @product.title %> Bill</h1>
						<p class="gray-text">Item #<%= @product.sku %></p>
						<hr>
			</div> 
			<%= image_tag @product.image.url, alt: @product.title, class: "product" %>
		</div> <!-- /column1 -->
		<div class="col-md-7 col-sm-6 col-xs-12">
				<h1 class="hidden-xs"><%= @product.title %> Bill</h1>
				<p class="gray-text hidden-xs">Item #<%= @product.sku %></p>
				<hr class="visible-xs">
				<p class="price"><%= number_to_currency @product.price %></p>
				<p class="star-rating-large five ir">Star Rating</p>

			<%= form_tag '/line_items', method: :post do %>	
				<%= hidden_field_tag :product_id, @product.id %>
				<%= number_field_tag :quantity, 1, min: 1, max: 100 %>
				
				<%= button_tag id: 'add-cart', class: 'btn btn-red btn-med' do %>
				<span class="glyphicon glyphicon-shopping-cart"> </span> Add to cart
				<% end %>


			<% end %>

				
				<!-- Nav tabs -->
				<ul class="nav nav-tabs">
					<li class="active"><a href="#details" data-toggle="tab">Details</a></li>
					<li><a href="#specs" data-toggle="tab">Specs</a></li>
					<li><a href="#reviews" data-toggle="tab">Reviews</a></li>
				</ul> <!-- / .nav-tabs -->
		 	<!-- Tab panes -->
			<div class="tab-content">
				<div class="tab-pane fade in active" id="details">
					<p><%= raw @redcarpet.render @product.description %></p>
				</div> <!-- / details -->
				<div class="tab-pane fade" id="specs">
					<%= raw @redcarpet.render @product.specs %>
				</div> <!-- / #specs -->
				<div class="tab-pane fade" id="reviews">
					Coming Soon! # yeah right	? Not if I keep having to do this shite section over and over			 <hr>
			</div> <!-- / tab panes -->
			</div> <!-- / tab content -->
		</div> <!-- /column2 --> 
	</div> <!-- /.row --> 

app/views/shared/_get_nutty.html.erb
<div class="jumbotron">
	<div class="container">
		<h1>Ready to get <span id="nutty"> Nutty?</span></h1>
		<p>Find clever, witty, and hilarious gifts for That Nutty Guy you know. Guaranteed to make your friends and family smile.</p>
		<p><span id="gift-icon" class="ir"></span><a href="#">Try out our Gift Finder</a></p>
	</div> <!--/.container -->
</div> <!--/.jumbotron-->